version: '3.8'

services:
  amplifica-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: werikoliveira/amplificagroup:latest
    container_name: amplifica-marketing-app
    restart: always
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - NODE_ENV=production
      - API_KEY=${API_KEY:-amplifica_sec_key_991951381_2026}
    volumes:
      - sqlite_data:/app/server/data

volumes:
  sqlite_data:
    driver: local
